spring:
  application:
    name: order-service
  h2:
    console:
      enabled: true
  datasource:
    url: jdbc:postgresql://localhost:5432/order_db
    username: aditya
    password: aditya

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect

  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest

management:
  endpoints:
    web:
      exposure:
        include: "*"


server:
  port: 8083


eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
    register-with-eureka: true
    fetch-registry: true





